import { useState } from "react";
import { Eye, MoreHorizontal, Download, FileText, Trash2, Copy } from "lucide-react";
import ReportStatusBadge from "./ReportStatusBadge";
import EmptyState from "@/components/common/EmptyState";

function ReportsTable({ reports, onViewDetails }) {
  const [openMenuId, setOpenMenuId] = useState(null);

  const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleString("en-US", {
      month: "short",
      day: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    });
  };

  const toggleMenu = (id) => {
    setOpenMenuId(openMenuId === id ? null : id);
  };

  const closeMenu = () => {
    setOpenMenuId(null);
  };

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/30">
              <th className="px-5 py-3 text-left text-xs font-medium text-muted-foreground">
                Report ID
              </th>
              <th className="px-5 py-3 text-left text-xs font-medium text-muted-foreground">
                Report Name
              </th>
              <th className="hidden px-5 py-3 text-left text-xs font-medium text-muted-foreground md:table-cell">
                Report Type
              </th>
              <th className="hidden px-5 py-3 text-left text-xs font-medium text-muted-foreground lg:table-cell">
                Generated Date
              </th>
              <th className="hidden px-5 py-3 text-left text-xs font-medium text-muted-foreground xl:table-cell">
                Generated By
              </th>
              <th className="hidden px-5 py-3 text-left text-xs font-medium text-muted-foreground sm:table-cell">
                File Size
              </th>
              <th className="px-5 py-3 text-left text-xs font-medium text-muted-foreground">
                Status
              </th>
              <th className="px-5 py-3 text-right text-xs font-medium text-muted-foreground">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {reports.map((report) => (
              <tr
                key={report.id}
                className="transition-colors hover:bg-muted/20"
              >
                <td className="whitespace-nowrap px-5 py-3 font-mono text-xs text-foreground">
                  {report.id}
                </td>
                <td className="px-5 py-3">
                  <div className="flex items-center gap-2">
                    <FileText className="size-4 shrink-0 text-muted-foreground" />
                    <span className="font-medium text-foreground">{report.name}</span>
                  </div>
                </td>
                <td className="hidden whitespace-nowrap px-5 py-3 md:table-cell">
                  <span className="inline-flex items-center rounded-md border border-border bg-muted px-2 py-0.5 text-xs font-medium text-foreground">
                    {report.type}
                  </span>
                </td>
                <td className="hidden whitespace-nowrap px-5 py-3 text-xs text-muted-foreground lg:table-cell">
                  {formatDate(report.generatedDate)}
                </td>
                <td className="hidden whitespace-nowrap px-5 py-3 text-foreground xl:table-cell">
                  {report.generatedBy}
                </td>
                <td className="hidden whitespace-nowrap px-5 py-3 text-xs text-muted-foreground sm:table-cell">
                  {report.fileSize}
                </td>
                <td className="whitespace-nowrap px-5 py-3">
                  <ReportStatusBadge status={report.status} />
                </td>
                <td className="whitespace-nowrap px-5 py-3 text-right">
                  <div className="relative inline-block">
                    <button
                      onClick={() => toggleMenu(report.id)}
                      className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground"
                      aria-label="Actions"
                    >
                      <MoreHorizontal className="size-4" />
                    </button>
                    {openMenuId === report.id && (
                      <>
                        <div
                          className="fixed inset-0 z-10"
                          onClick={closeMenu}
                          aria-hidden="true"
                        />
                        <div className="absolute right-0 z-20 mt-1 w-44 rounded-lg border border-border bg-popover py-1 shadow-lg">
                          <button
                            onClick={() => {
                              onViewDetails(report);
                              closeMenu();
                            }}
                            className="flex w-full items-center gap-2 px-3 py-2 text-sm text-foreground hover:bg-muted"
                          >
                            <Eye className="size-4" aria-hidden="true" />
                            Preview Report
                          </button>
                          <button
                            onClick={closeMenu}
                            className="flex w-full items-center gap-2 px-3 py-2 text-sm text-foreground hover:bg-muted"
                          >
                            <Download className="size-4" aria-hidden="true" />
                            Download {report.format}
                          </button>
                          <button
                            onClick={closeMenu}
                            className="flex w-full items-center gap-2 px-3 py-2 text-sm text-foreground hover:bg-muted"
                          >
                            <Copy className="size-4" aria-hidden="true" />
                            Duplicate
                          </button>
                          <div className="my-1 border-t border-border" />
                          <button
                            onClick={closeMenu}
                            className="flex w-full items-center gap-2 px-3 py-2 text-sm text-destructive hover:bg-muted"
                          >
                            <Trash2 className="size-4" aria-hidden="true" />
                            Delete
                          </button>
                        </div>
                      </>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {reports.length === 0 && (
        <EmptyState
          icon={FileText}
          title="No reports found"
          description="Try adjusting your search or filter criteria"
        />
      )}
    </div>
  );
}

export default ReportsTable;
