import { X, FileText, Clock, Hash, Calendar, User, HardDrive, CheckCircle, AlertCircle, Loader } from "lucide-react";
import ReportStatusBadge from "./ReportStatusBadge";

function DetailRow({ label, value, mono = false, icon: Icon }) {
  return (
    <div className="flex items-start gap-3">
      {Icon && <Icon className="mt-0.5 size-4 shrink-0 text-muted-foreground" />}
      <div className="flex flex-col">
        <span className="text-xs text-muted-foreground">{label}</span>
        <span className={`text-sm text-foreground ${mono ? "font-mono" : ""}`}>
          {value || "N/A"}
        </span>
      </div>
    </div>
  );
}

function ReportPreviewDrawer({ report, onClose }) {
  if (!report) return null;

  const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    });
  };

  return (
    <>
      <div
        className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm transition-opacity"
        onClick={onClose}
        aria-hidden="true"
      />

      <div className="fixed inset-y-0 right-0 z-50 flex w-full max-w-lg flex-col border-l border-border bg-background shadow-2xl transition-transform duration-300 ease-in-out sm:max-w-xl">
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-8 items-center justify-center rounded-lg border border-info/20 bg-info/10">
              <FileText className="size-4 text-info" aria-hidden="true" />
            </div>
            <div>
              <h2 className="text-sm font-semibold text-foreground">Report Preview</h2>
              <p className="text-xs text-muted-foreground">{report.id}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground"
            aria-label="Close drawer"
          >
            <X className="size-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          <div className="space-y-6">
            <div className="flex items-center gap-4">
              <ReportStatusBadge status={report.status} />
              <span className="inline-flex items-center rounded-md border border-border bg-muted px-2 py-0.5 text-xs font-medium text-foreground">
                {report.type}
              </span>
              <span className="inline-flex items-center rounded-md border border-border bg-muted px-2 py-0.5 text-xs font-medium text-foreground">
                {report.format}
              </span>
            </div>

            <div className="rounded-lg border border-border bg-muted/30 p-4">
              <h3 className="text-sm font-medium text-foreground">{report.name}</h3>
              <p className="mt-2 text-xs text-muted-foreground leading-relaxed">
                {report.summary}
              </p>
            </div>

            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-foreground">Report Metadata</h4>
              <div className="grid grid-cols-2 gap-4">
                <DetailRow label="Report ID" value={report.id} mono icon={Hash} />
                <DetailRow label="Generated Date" value={formatDate(report.generatedDate)} icon={Calendar} />
                <DetailRow label="Generated By" value={report.generatedBy} icon={User} />
                <DetailRow label="Time Range" value={report.timeRange} icon={Clock} />
                <DetailRow label="File Size" value={report.fileSize} icon={HardDrive} />
                <DetailRow label="Generation Time" value={report.generationTime} icon={Clock} />
              </div>
            </div>

            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-foreground">Included Sections</h4>
              <div className="space-y-2">
                {report.sections.map((section, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"
                  >
                    <CheckCircle className="size-3.5 text-success" />
                    <span className="text-sm text-foreground">{section}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-foreground">Generation Details</h4>
              <div className="rounded-lg border border-border p-4">
                <div className="flex items-center gap-3">
                  {report.status === "Completed" && (
                    <CheckCircle className="size-5 text-success" />
                  )}
                  {report.status === "Processing" && (
                    <Loader className="size-5 text-info animate-spin" />
                  )}
                  {report.status === "Failed" && (
                    <AlertCircle className="size-5 text-destructive" />
                  )}
                  <div>
                    <p className="text-sm font-medium text-foreground">
                      {report.status === "Completed" && "Report Generated Successfully"}
                      {report.status === "Processing" && "Report is Being Generated..."}
                      {report.status === "Failed" && "Report Generation Failed"}
                      {report.status === "Archived" && "Report Archived"}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {report.status === "Completed" && `Completed in ${report.generationTime}`}
                      {report.status === "Processing" && "Please wait..."}
                      {report.status === "Failed" && "An error occurred during generation"}
                      {report.status === "Archived" && "This report has been archived"}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="border-t border-border px-6 py-4">
          <div className="flex gap-3">
            <button className="flex-1 inline-flex items-center justify-center gap-2 rounded-lg border border-border bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-muted">
              <FileText className="size-4" aria-hidden="true" />
              Download {report.format}
            </button>
            <button className="flex-1 inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/80">
              <FileText className="size-4" aria-hidden="true" />
              Open Full Report
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

export default ReportPreviewDrawer;
